'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState,useRef} from 'react';
import {Icon} from './icon';
import {useShop} from './shop-provider';
export function Mark(){return <svg viewBox="0 0 32 32" width="29" height="29" fill="none" aria-hidden="true"><path d="M16 2 30 25H2L16 2Z" stroke="currentColor" strokeWidth="1.3"/><path d="m16 2 5 23M16 2 11 25M2 25l24-7M6 18l24 7" stroke="currentColor" strokeWidth="1.1"/></svg>;}
export function Header(){const shop=useShop(),path=usePathname();const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);useEffect(()=>{const update=()=>setScrolled(window.scrollY>80);update();window.addEventListener('scroll',update,{passive:true});return ()=>window.removeEventListener('scroll',update);},[]);return <><a href="#main" className="skip-link">К содержимому</a><header className={`site-header ${scrolled?'scrolled':''}`} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus();}}}><div className="nav-island"><Link href="/" className="wordmark" aria-label="Shards — главная"><Mark/>Shards</Link><nav className={open?'main-nav is-open':'main-nav'} aria-label="Основная навигация"><Link href="/catalog" aria-current={path.startsWith('/catalog')?'page':undefined} onClick={()=>setOpen(false)}>Скины</Link><Link href="/#steam" onClick={()=>setOpen(false)}>Steam</Link><Link href="/#gift-cards" onClick={()=>setOpen(false)}>Карты Apple</Link><Link href="/#duo" onClick={()=>setOpen(false)}>Дуэт <span className="mini-star">✳</span></Link></nav><button ref={menuButton} className="icon-button mobile-toggle" aria-label={open?'Закрыть меню':'Открыть меню'} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name={open?'close':'menu'}/></button></div><div className="header-actions"><Link href="/catalog?saved=1" className="icon-button header-saved" aria-label="Избранное"><Icon name="heart"/></Link><Link href="/cart" className="cart-link" aria-label={`Корзина, товаров: ${shop.cart.length}`}><Icon name="cart"/><span>{shop.cart.length}</span></Link>{shop.loggedIn?<Link className="header-login" href="/account"><Icon name="user"/><span>Кабинет</span></Link>:<button className="header-login" onClick={shop.login}><Icon name="steam"/><span>Войти</span></button>}</div></header></>;}
export function Footer(){const ref=useRef<HTMLDivElement>(null);return <footer className="shards-footer"><div className="footer-top"><div><Link href="/" className="wordmark"><Mark/>Shards</Link><p>Твоя игра.<br/>В новом свете.</p></div><nav aria-label="Внизу страницы"><Link href="/catalog">Выбрать скин ↗</Link><Link href="/#duo">Собрать дуэт ↗</Link><Link href="/#compare">Сравнить скины ↗</Link></nav><nav aria-label="Сервисы"><Link href="/#steam">Пополнение Steam</Link><Link href="/#gift-cards">Карты Apple</Link><Link href="/account">Личный кабинет</Link><Link href="/#faq">Вопросы и ответы</Link></nav><a className="back-top" href="#main" aria-label="Вернуться наверх">↑</a></div><div ref={ref} className="footer-sculpture" onPointerMove={e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();ref.current?.style.setProperty('--shift',`${((e.clientX-r.left)/r.width-.5)*28}px`);ref.current?.style.setProperty('--lift',`${((e.clientY-r.top)/r.height)*18}px`);}} onPointerLeave={()=>{ref.current?.style.setProperty('--shift','0px');ref.current?.style.setProperty('--lift','0px');}}><span aria-hidden="true" className="footer-echo echo-three">Shards</span><span aria-hidden="true" className="footer-echo echo-two">Shards</span><span aria-hidden="true" className="footer-echo echo-one">Shards</span><Link href="/catalog" aria-label="Shards — открыть каталог" className="footer-main-word">Shards</Link><span className="footer-spark" aria-hidden="true">✳</span></div><div className="footer-baseline"><span>© Shards, 2026</span><span>Скины CS2 · Steam · Apple</span><span>1 ₽ = 1,6 Shards</span></div></footer>;}
