'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState,useRef} from 'react';
import {Icon} from './icon';
import {useShop} from './shop-provider';
export function Mark(){return <svg viewBox="0 0 32 32" width="29" height="29" fill="none" aria-hidden="true"><path d="M26.4 4H12.1C6.9 4 3.7 7.1 3.7 11.4c0 3.8 2.6 6.1 7.2 7.2l10.2 2.4c1.6.4 2.3 1 2.3 2.1 0 1.2-.9 2-2.5 2H6.2l1.8 4h13.1c5.2 0 8.6-2.8 8.6-7 0-3.7-2.7-5.8-7.3-6.9l-10.1-2.4c-1.4-.3-2.1-.9-2.1-1.9 0-1.2.9-2 2.5-2h15.5L26.4 4Z" fill="currentColor"/><path d="m8.2 9.5 4-2.2h11.6l-1.1 2.2H12.4c-1.9 0-3.2.7-4.2 2Zm15.6 13.1c0 1.2-.9 2-2.5 2H9.6l-1.5 2.5h11.9c2.2 0 3.6-1 3.8-2.8Z" fill="currentColor" opacity=".42"/></svg>;}
export function Header(){const shop=useShop(),path=usePathname();const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);useEffect(()=>{const update=()=>setScrolled(window.scrollY>80);update();window.addEventListener('scroll',update,{passive:true});return ()=>window.removeEventListener('scroll',update);},[]);return <><a href="#main" className="skip-link">К содержимому</a><header className={`site-header ${scrolled?'scrolled':''}`} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus();}}}><div className="nav-island"><Link href="/" className="wordmark" aria-label="Shards — главная"><Mark/>Shards</Link><nav className={open?'main-nav is-open':'main-nav'} aria-label="Основная навигация"><Link href="/catalog" aria-current={path.startsWith('/catalog')?'page':undefined} onClick={()=>setOpen(false)}>Скины</Link><Link href="/#steam" onClick={()=>setOpen(false)}>Steam</Link><Link href="/#gift-cards" onClick={()=>setOpen(false)}>Карты Apple</Link><Link href="/#duo" onClick={()=>setOpen(false)}>Дуэт <span className="mini-star">✳</span></Link></nav><button ref={menuButton} className="icon-button mobile-toggle" aria-label={open?'Закрыть меню':'Открыть меню'} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name={open?'close':'menu'}/></button></div><div className="header-actions"><Link href="/catalog?saved=1" className="icon-button header-saved" aria-label="Избранное"><Icon name="heart"/></Link><Link href="/cart" className="cart-link" aria-label={`Корзина, товаров: ${shop.cart.length}`}><Icon name="cart"/><span>{shop.cart.length}</span></Link>{shop.loggedIn?<Link className="header-login" href="/account"><Icon name="user"/><span>Кабинет</span></Link>:<button className="header-login" onClick={shop.login}><Icon name="steam"/><span>Войти</span></button>}</div></header></>;}
export function Footer(){const ref=useRef<HTMLDivElement>(null);return <footer className="shards-footer"><div className="footer-top"><div><Link href="/" className="wordmark"><Mark/>Shards</Link><p>Твоя игра.<br/>В новом свете.</p></div><nav aria-label="Внизу страницы"><Link href="/catalog">Выбрать скин ↗</Link><Link href="/#duo">Собрать дуэт ↗</Link><Link href="/#compare">Сравнить скины ↗</Link></nav><nav aria-label="Сервисы"><Link href="/#steam">Пополнение Steam</Link><Link href="/#gift-cards">Карты Apple</Link><Link href="/account">Личный кабинет</Link><Link href="/#faq">Вопросы и ответы</Link></nav><a className="back-top" href="#main" aria-label="Вернуться наверх">↑</a></div><div ref={ref} className="footer-sculpture" onPointerMove={e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();ref.current?.style.setProperty('--shift',`${((e.clientX-r.left)/r.width-.5)*28}px`);ref.current?.style.setProperty('--lift',`${((e.clientY-r.top)/r.height)*18}px`);}} onPointerLeave={()=>{ref.current?.style.setProperty('--shift','0px');ref.current?.style.setProperty('--lift','0px');}}><span aria-hidden="true" className="footer-echo echo-three">Shards</span><span aria-hidden="true" className="footer-echo echo-two">Shards</span><span aria-hidden="true" className="footer-echo echo-one">Shards</span><Link href="/catalog" aria-label="Shards — открыть каталог" className="footer-main-word">Shards</Link><span className="footer-spark" aria-hidden="true">✳</span></div><div className="footer-baseline"><span>© Shards, 2026</span><span>Скины CS2 · Steam · Apple</span><span>1 ₽ = 1,6 Shards</span></div></footer>;}
